// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA53bP_C76X1MDVqFHKcqS5MKqawFhydjg',
    appId: '1:888353347157:web:b0764592382d9f189de6dc',
    messagingSenderId: '888353347157',
    projectId: 'flutter-chat-74106',
    authDomain: 'flutter-chat-74106.firebaseapp.com',
    storageBucket: 'flutter-chat-74106.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGqTx6qupe_QyLiUEH_4QOOnh7Qj2MKEY',
    appId: '1:888353347157:android:717791e908304a289de6dc',
    messagingSenderId: '888353347157',
    projectId: 'flutter-chat-74106',
    storageBucket: 'flutter-chat-74106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdUTYoMjQ9Di3WogGlhctiQ9uPuQx88aI',
    appId: '1:888353347157:ios:2a48cbb97fa52e489de6dc',
    messagingSenderId: '888353347157',
    projectId: 'flutter-chat-74106',
    storageBucket: 'flutter-chat-74106.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdUTYoMjQ9Di3WogGlhctiQ9uPuQx88aI',
    appId: '1:888353347157:ios:ae35ad9cf507627c9de6dc',
    messagingSenderId: '888353347157',
    projectId: 'flutter-chat-74106',
    storageBucket: 'flutter-chat-74106.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
